version: '3.8'

services:
  # FastAPI Backend
  backend:
    build:
      context: .  # Use project root as build context
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - CORS_ORIGINS=http://localhost:3000,http://localhost:80
    volumes:
      - ./data:/app/data
      - ./forecasting:/app/forecasting
      - ./config.py:/app/config.py
    depends_on:
      - postgres
    restart: unless-stopped

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:8000
    restart: unless-stopped

  # PostgreSQL Database (for future user management and forecast storage)
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: datect
      POSTGRES_USER: datect_user
      POSTGRES_PASSWORD: datect_password_change_in_production
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Nginx (Production reverse proxy)
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    profiles:
      - production

volumes:
  postgres_data: