# DATect Docker Compose Configuration
# ===================================
# 
# Orchestrates the streamlined DATect forecasting system

services:
  # Main Data Processing Service
  datect-processor:
    build: .
    container_name: datect-data-processor
    volumes:
      - ./data:/app/data
      - ./outputs:/app/outputs
    environment:
      - DATECT_ENV=production
      - PYTHONPATH=/app
    command: python dataset-creation.py
    
  # Real-time Forecasting Dashboard
  datect-realtime:
    build: .
    container_name: datect-realtime-dashboard
    ports:
      - "8065:8065"
    volumes:
      - ./data:/app/data
      - ./outputs:/app/outputs
    environment:
      - DATECT_ENV=production
      - PYTHONPATH=/app
      - FORECAST_MODE=realtime
    command: python modular-forecast.py
    depends_on:
      - datect-processor

  # Retrospective Analysis Dashboard
  datect-retrospective:
    build: .
    container_name: datect-retrospective-dashboard
    ports:
      - "8071:8071"
    volumes:
      - ./data:/app/data
      - ./outputs:/app/outputs
    environment:
      - DATECT_ENV=production
      - PYTHONPATH=/app
      - FORECAST_MODE=retrospective
    command: python modular-forecast.py
    depends_on:
      - datect-processor

  # Optional: Scientific Analysis Service
  datect-analysis:
    build: .
    container_name: datect-analysis
    volumes:
      - ./data:/app/data
      - ./analysis:/app/analysis
      - ./outputs:/app/outputs
    environment:
      - DATECT_ENV=production
      - PYTHONPATH=/app
    command: python -c "print('Analysis tools available in /app/analysis/')"
    depends_on:
      - datect-processor

volumes:
  datect-data:
  datect-outputs: